# Generated by Django 2.1.5 on 2019-04-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('django_celery_beat', '0006_periodictask_priority'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create By')),
                ('asset', models.ManyToManyField(blank=True, related_name='asset_task', to='asset.Asset', verbose_name='Asset')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Create User')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.KeyManage', verbose_name='Scheduled Name')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project', verbose_name='User Project')),
                ('scheduled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_task', to='django_celery_beat.PeriodicTask', verbose_name='Scheduled Name')),
            ],
            options={
                'verbose_name': 'Scheduled Tasks',
                'verbose_name_plural': 'Scheduled Tasks',
                'db_table': 'scheduledtasks',
            },
        ),
        migrations.CreateModel(
            name='ScriptsManage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Script Name')),
                ('type', models.IntegerField(choices=[(0, 'shell'), (1, 'python'), (2, 'bat')], verbose_name='Script Type')),
                ('args', models.CharField(blank=True, max_length=255, null=True, verbose_name='Script Args')),
                ('content', models.TextField(verbose_name='Script Content')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Script Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create By')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Create User')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Scripts Manage',
                'verbose_name_plural': 'Scripts Manage',
                'db_table': 'scriptsmanage',
            },
        ),
        migrations.CreateModel(
            name='TaskScheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Task Name')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Orchestration Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create By')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Create User')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Task Scheduling',
                'verbose_name_plural': 'Task Scheduling',
                'db_table': 'taskscheduling',
            },
        ),
        migrations.CreateModel(
            name='TaskSchedulScripts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Execution order')),
                ('status', models.IntegerField(choices=[(0, '失败退出'), (1, '失败继续执行')], default=0, verbose_name='Execution Status')),
                ('delaytime', models.IntegerField(blank=True, null=True, verbose_name='Delay Time Execution')),
                ('scripts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.ScriptsManage', verbose_name='Scritps Name')),
            ],
            options={
                'verbose_name': 'Task Schedul Scripts',
                'verbose_name_plural': 'Task Schedul Scripts',
                'db_table': 'taskschedulscripts',
            },
        ),
        migrations.CreateModel(
            name='UpdateConfigLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Config Type')),
                ('content', models.TextField(verbose_name='Config Histroy Content')),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Update By')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Update User')),
            ],
            options={
                'verbose_name': 'Update Config Log',
                'verbose_name_plural': 'Update Config Log',
                'db_table': 'updateconfiglog',
            },
        ),
        migrations.AddField(
            model_name='taskscheduling',
            name='task_scripts',
            field=models.ManyToManyField(blank=True, to='jobs.TaskSchedulScripts', verbose_name='Task Schedul Scripts'),
        ),
        migrations.AddField(
            model_name='scriptsmanage',
            name='update',
            field=models.ManyToManyField(blank=True, to='jobs.UpdateConfigLog', verbose_name='Update Log'),
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='scheduling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.TaskScheduling', verbose_name='Task Scheduling Name'),
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='scritps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.ScriptsManage', verbose_name='Scritps Name'),
        ),
    ]
