# Generated by Django 2.1.5 on 2019-10-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruse',
            name='mini_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Server Use Describe Name'),
        ),
        migrations.AlterField(
            model_name='work_env',
            name='mini_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Work_Env Describe Name'),
        ),
    ]
