# Generated by Django 2.1.5 on 2019-04-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Batch Cmd'), (1, 'Batch Scripts'), (2, 'File Distribution'), (3, 'Batch Task'), (4, 'Crontab Task')], null=True, verbose_name='Jobs Type')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('job_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Job Name')),
                ('remote_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote Path')),
                ('operator', models.CharField(blank=True, max_length=64, null=True, verbose_name='Operator')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.KeyManage', verbose_name='Jobs Exec Key')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project', verbose_name='Jobs Project')),
            ],
            options={
                'verbose_name': 'Jobs Results',
                'verbose_name_plural': 'Jobs Results',
                'db_table': 'jobsresults',
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128, verbose_name='User')),
                ('change_by', models.CharField(max_length=128, verbose_name='Change by')),
                ('remote_addr', models.CharField(blank=True, max_length=15, null=True, verbose_name='Remote addr')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password Change Log',
                'verbose_name_plural': 'Password Change Log',
                'db_table': 'passwordchangelog',
            },
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='Client Address')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Request Date Time')),
                ('type', models.IntegerField(choices=[(0, 'GET'), (1, 'POST')], verbose_name='Request Type')),
                ('get_full_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Request Full Path')),
                ('post_body', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Request Post Body')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UserName')),
            ],
            options={
                'verbose_name': 'Request Record',
                'verbose_name_plural': 'Request Record',
                'db_table': 'requestrecord',
            },
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Task ID')),
                ('log', models.CharField(blank=True, max_length=128, null=True, verbose_name='Log Info')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='Total Time')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.Asset', verbose_name='Tasks Asset')),
            ],
            options={
                'verbose_name': 'Task Schedule Table',
                'verbose_name_plural': 'Task Schedule Table',
                'db_table': 'taskschedule',
            },
        ),
        migrations.AddField(
            model_name='jobsresults',
            name='task_schedule',
            field=models.ManyToManyField(blank=True, to='audit.TaskSchedule', verbose_name='Jobs Schedule'),
        ),
    ]
