# Generated by Django 2.1.5 on 2019-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0002_auto_20191009_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='pro_env',
            field=models.CharField(max_length=10, verbose_name='运行环境'),
        ),
    ]
