# Generated by Django 2.1.5 on 2019-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0005_auto_20191011_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '部署状态记录',
                'verbose_name_plural': '部署状态记录',
                'db_table': 'deploystatus',
            },
        ),
        migrations.AlterModelOptions(
            name='updateinfo',
            options={'ordering': ['-create_time'], 'verbose_name': '服务更新记录', 'verbose_name_plural': '服务更新记录'},
        ),
    ]
