# Generated by Django 2.1.5 on 2019-10-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0006_auto_20191012_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploystatus',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deploystatus',
            name='serverName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='deploystatus',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
