# Generated by Django 2.1.5 on 2019-10-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0007_auto_20191012_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploystatus',
            old_name='createTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='deploystatus',
            old_name='serverName',
            new_name='server_name',
        ),
    ]
