# Generated by Django 2.1.5 on 2019-10-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0009_auto_20191019_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploystatus',
            old_name='uuid',
            new_name='build_uuid',
        ),
    ]
