# Generated by Django 2.1.5 on 2019-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0010_auto_20191019_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='build_uuid',
            field=models.UUIDField(null=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
