# Generated by Django 2.1.5 on 2019-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0013_auto_20191023_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='branch_env',
            field=models.CharField(max_length=50, verbose_name='上线记录'),
        ),
    ]
