# Generated by Django 2.1.5 on 2019-10-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0014_auto_20191023_1105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('server_name', 'branch_env')},
        ),
    ]
