# Generated by Django 2.1.5 on 2019-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0015_auto_20191023_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
