# Generated by Django 2.1.5 on 2019-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0017_auto_20191023_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinfo',
            name='build_uuid',
        ),
        migrations.AddField(
            model_name='updateinfo',
            name='build_gitid',
            field=models.UUIDField(null=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='updateinfo',
            name='git_commit',
            field=models.CharField(max_length=200, null=True, verbose_name='Git Commit'),
        ),
        migrations.AlterField(
            model_name='deploystatus',
            name='env_name',
            field=models.CharField(max_length=50, null=True, verbose_name='环境名称'),
        ),
    ]
