# Generated by Django 2.1.5 on 2019-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0020_auto_20191103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='build_uuid',
            field=models.UUIDField(null=True, verbose_name='uuid'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('server_name', 'branch_env', 'build_uuid')},
        ),
    ]
