# Generated by Django 2.1.5 on 2019-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0021_auto_20191105_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploystatus',
            name='branch_env',
            field=models.CharField(default='master', max_length=50, verbose_name='上线分支'),
        ),
    ]
