# Generated by Django 2.1.5 on 2019-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0022_deploystatus_branch_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codefreeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('checkoutbranch', models.CharField(max_length=100)),
                ('codefreeze', models.CharField(blank=True, max_length=100, null=True)),
                ('gittag', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('gitadd', models.ManyToManyField(to='kube.GitInfo')),
            ],
            options={
                'verbose_name': 'Code freeze',
                'verbose_name_plural': 'Code freeze',
                'permissions': (('查看', ''),),
            },
        ),
    ]
