# Generated by Django 2.1.5 on 2019-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0023_codefreeze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codefreeze',
            options={'verbose_name': 'Code freeze', 'verbose_name_plural': 'Code freeze'},
        ),
        migrations.RenameField(
            model_name='codefreeze',
            old_name='codefreeze',
            new_name='code_freeze',
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='checkoutbranch',
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='gitadd',
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='gittag',
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='projectname',
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='checkout_branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='git_add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='git_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
