# Generated by Django 2.1.5 on 2019-11-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0024_auto_20191105_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codefreeze',
            options={'verbose_name': '封板', 'verbose_name_plural': '封板'},
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='git_add',
        ),
    ]
