# Generated by Django 2.1.5 on 2019-11-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0025_auto_20191105_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codefreeze',
            name='project_name',
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='project_name',
            field=models.ManyToManyField(to='kube.GitInfo'),
        ),
        migrations.AlterModelTable(
            name='codefreeze',
            table='codefreeze',
        ),
    ]
