# Generated by Django 2.1.5 on 2019-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0026_auto_20191105_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='branch_env',
            field=models.CharField(default='master', max_length=50, verbose_name='分支信息'),
        ),
        migrations.RemoveField(
            model_name='codefreeze',
            name='project_name',
        ),
        migrations.AddField(
            model_name='codefreeze',
            name='project_name',
            field=models.CharField(default=2, max_length=100, verbose_name='项目名'),
            preserve_default=False,
        ),
    ]
