# Generated by Django 2.1.5 on 2019-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0029_auto_20191107_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
    ]
