# Generated by Django 2.1.5 on 2019-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0032_auto_20191107_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(default='latest', max_length=50, verbose_name='latest'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('server_name', 'status')},
        ),
    ]
