# Generated by Django 2.1.5 on 2019-11-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0033_auto_20191107_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('server_name', 'status', 'branch_env')},
        ),
    ]
