# Generated by Django 2.1.5 on 2019-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0034_auto_20191107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='server_name',
            field=models.CharField(max_length=100, verbose_name='服务名称'),
        ),
    ]
